### ISSUE TITLE
Wrong thermal source used

### ISSUE THREAD

**Issue by ghost** [FractalUK/KSPInterstellar#22]
If any reactor is placed on the same craft as a Microwave thermal receiver the wrong thermal source is reported in the VAB thermal mechanics helper. This results in crafts that need an abnormally large number of radiators.

I discovered this while creating a craft for long durations science missions. I wanted to shut down my big thrusting reactor while in orbit of Eeloo and just use my Microwave sats to provide the needed 5Mw of power. However, I found that if I placed a 1.25 thermal microwave receiver and a 1.25m generator into the stack the 1.25 generator would go into a negative efficiency shortly after launch and stop generating power altogether. The only way to resolve this was to place 30 Huge fully upgraded radiators on the ship. I only had a 3.75 fission, 3.75 generator, a 1.25 generator and a thermal microwave receiver on the ship. The previous designed ship didnt have the microwave receiver and only needed 1 Huge upgraded radiator to function normally although I typically use two because the symmetry looked nicer.

Anyway, steps to reproduce and reported info in the VAB thermal helper.

1: place 3.75 Fission Aegletes ractor. (although I have seen it can be any reactor)
2: place 1 Huge fully upgraded radiator
### Thermal report says
- 1 AU
- Total Heat Production: 9.00 GW
- 100% Thermal Source Temp at **15590.0K**
- 30% Thermal Source Temp at **15590.0K**
- Radiator Max Diss **13.61GW**
- Radiator Resting Temp 3155.9K at 100%
- Radiator Resting Temp 2335.7K at 30%

3: place any one of the MTER microwave thermal receivers into the stack with the fission and radiator combo created in step 1 & 2
### Thermal Report says
- 1 AU
- Total Heat Production: 9.00 GW
- 100% Thermal Source Temp at **1500.0K**
- 30% Thermal Source Temp at **1500.0K**
- Radiator Max Diss **459.3MW**
- Radiator Resting Temp 3155.9K at 100%
- Radiator Resting Temp 2335.7K at 30%

_note the radiator did not change in this report it was still a Fully upgraded huge radiator, only the MTER was added to the stack_

4: build a working orbital ship and send it into orbit with 2 generators. 1 for the fission reactor and 1 for the thermal microwave. In all my tests the generator associated with the microwave thermal will go into a negative efficiency shortly after liftoff and no longer will it produce energy. In my tests the microwave thermal receiver was receiving between 43Mw and 85Mw of microwave energy depending on orientation with the Kerbin horizon.

**Comment by FractalUK** [comment]
This is not a bug - the different reactors, in this case a fission and a microwave thermal receiver have different associated temperatures.  The microwave thermal receiver works at particularly low temperature which means that if you switch it on late in flight, it's very possible with upgraded radiators you'll start with a higher radiator than "reactor" temperature - and that means 0 power can be produced by the generators.

If you want to use thermal receivers effectively, you're going to have plan around keeping them cooler and thus using a lot more radiators.  The thermal helper tries to help you plan for that.

If you just want 5MW of power though, why are you using a thermal receiver?  Just use a standard receiver, then you don't have this problem.  The only advantage to a thermal receiver is you can use it for thermal rockets, otherwise you just end up with less power and more design constraints.

**Comment by ghost** [comment]
Because you dont have to point a thermal receiver and it would require less repeaters around the solar system. But thats cool I'll redesign. 

Maybe an auto pointing feature for the antenna would be nice.
